# Generated by Django 6.0.5 on 2026-06-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default=1, max_length=150, verbose_name='Тема обращения'),
            preserve_default=False,
        ),
    ]
